# Generated by Django 5.1.2 on 2025-04-19 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_user_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='expression',
            new_name='experession',
        ),
    ]
