# Generated by Django 5.1.2 on 2025-04-25 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_client_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('price', models.FloatField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('product_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_added', models.DateTimeField()),
            ],
        ),
    ]
