# Generated by Django 5.1.2 on 2025-04-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='product_main_img',
        ),
        migrations.AddField(
            model_name='product',
            name='product_sec_img1',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sec_img2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='product',
            name='product_sec_img3',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
