# Generated by Django 5.1.2 on 2025-04-28 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_category_product_main_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_main_img',
            new_name='image',
        ),
    ]
