# Generated by Django 5.1.2 on 2025-04-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_rename_product_main_img_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pic.jpg', null=True, upload_to=''),
        ),
    ]
