# Generated by Django 5.1.4 on 2025-06-11 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_client_profile_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='order',
            new_name='oorder',
        ),
    ]
