# Generated by Django 5.1.4 on 2025-06-11 10:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_rename_order_orderitem_oorder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='oorder',
            new_name='order',
        ),
    ]
