# Generated by Django 5.1.4 on 2025-06-11 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_oorder_orderitem_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='User',
            new_name='user',
        ),
    ]
