# Generated by Django 5.2.4 on 2025-07-12 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_user_client_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pic.jpg', null=True, upload_to='ecom/profile_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ecom/products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sec_img1',
            field=models.ImageField(blank=True, null=True, upload_to='ecom/products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sec_img2',
            field=models.ImageField(blank=True, null=True, upload_to='ecom/products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sec_img3',
            field=models.ImageField(blank=True, null=True, upload_to='ecom/products_images'),
        ),
    ]
