# Generated by Django 5.2.4 on 2025-07-12 19:08

import storages.backends.s3
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_client_profile_pic_alter_product_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='profile_pic',
            field=models.ImageField(blank=True, default='images/profile_pic.jpg', null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecom/profile_images/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecom/products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sec_img1',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecom/products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sec_img2',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecom/products_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_sec_img3',
            field=models.ImageField(blank=True, null=True, storage=storages.backends.s3.S3Storage(), upload_to='ecom/products_images'),
        ),
    ]
